/**
 * Заготовки стоимости для калькулятора: ориентировочные цены новых автомобилей в
 * Казахстане, ₸. Нужны, когда на kolesa.kz нет объявлений модели или сайт недоступен:
 * клиент сразу видит правдоподобный расчет, а цену потом сверяет с продавцом. Это не
 * данные клиента: в черновик заявки цена попадает неподтвержденной.
 *
 * Ключ модели — «МАРКА|ПЕРВОЕ СЛОВО МОДЕЛИ» в верхнем регистре, как в каталоге банка.
 */
import type { LeaseModel } from "./types";

const M = 1_000_000;

export const MODEL_PRESETS: Record<string, number> = {
  // Toyota
  "TOYOTA|COROLLA": 13.5 * M,
  "TOYOTA|CAMRY": 19 * M,
  "TOYOTA|RAV4": 18 * M,
  "TOYOTA|C-HR": 15 * M,
  "TOYOTA|HIGHLANDER": 30 * M,
  "TOYOTA|FORTUNER": 25 * M,
  "TOYOTA|HILUX": 21 * M,
  "TOYOTA|LAND": 45 * M,
  "TOYOTA|LC300": 55 * M,
  "TOYOTA|LC": 45 * M,
  "TOYOTA|4RUNNER": 38 * M,
  "TOYOTA|HIACE": 24 * M,
  "TOYOTA|ALPHARD": 55 * M,
  "TOYOTA|SIENNA": 35 * M,
  "TOYOTA|PRIUS": 16 * M,
  "TOYOTA|BZ3": 14 * M,
  "TOYOTA|BZ": 17 * M,
  "TOYOTA|YARIS": 10 * M,
  "TOYOTA|CROWN": 30 * M,
  // Hyundai
  "HYUNDAI|ACCENT": 9.5 * M,
  "HYUNDAI|SOLARIS": 8.5 * M,
  "HYUNDAI|ELANTRA": 12 * M,
  "HYUNDAI|AVANTE": 12 * M,
  "HYUNDAI|SONATA": 16 * M,
  "HYUNDAI|GRANDEUR": 22 * M,
  "HYUNDAI|CRETA": 11 * M,
  "HYUNDAI|BAYON": 10 * M,
  "HYUNDAI|VENUE": 9.5 * M,
  "HYUNDAI|KONA": 13 * M,
  "HYUNDAI|TUCSON": 16 * M,
  "HYUNDAI|SANTA": 22 * M,
  "HYUNDAI|PALISADE": 28 * M,
  "HYUNDAI|MUFASA": 13 * M,
  "HYUNDAI|CUSTIN": 17 * M,
  "HYUNDAI|STARIA": 23 * M,
  "HYUNDAI|STAREX": 18 * M,
  "HYUNDAI|H-1": 18 * M,
  "HYUNDAI|PORTER": 11 * M,
  "HYUNDAI|IONIQ": 20 * M,
  "HYUNDAI|I30": 11 * M,
  // Kia
  "KIA|RIO": 9 * M,
  "KIA|PICANTO": 7 * M,
  "KIA|MORNING": 7 * M,
  "KIA|RAY": 7.5 * M,
  "KIA|CERATO": 11.5 * M,
  "KIA|K3": 11.5 * M,
  "KIA|K4": 12 * M,
  "KIA|K5": 15 * M,
  "KIA|OPTIMA": 14 * M,
  "KIA|K7": 20 * M,
  "KIA|K8": 22 * M,
  "KIA|K9": 35 * M,
  "KIA|K900": 35 * M,
  "KIA|STINGER": 24 * M,
  "KIA|CEED": 11 * M,
  "KIA|XCEED": 12 * M,
  "KIA|SOUL": 10.5 * M,
  "KIA|SELTOS": 11.5 * M,
  "KIA|SONET": 9.5 * M,
  "KIA|STONIC": 9.5 * M,
  "KIA|NIRO": 14 * M,
  "KIA|SPORTAGE": 15 * M,
  "KIA|SORENTO": 21 * M,
  "KIA|MOHAVE": 28 * M,
  "KIA|TELLURIDE": 30 * M,
  "KIA|CARNIVAL": 25 * M,
  "KIA|SEDONA": 22 * M,
  "KIA|CARENS": 11 * M,
  "KIA|EV5": 17 * M,
  "KIA|EV6": 22 * M,
  "KIA|EV9": 35 * M,
  "KIA|BONGO": 11 * M,
  // Chevrolet / Ravon / Daewoo
  "CHEVROLET|COBALT": 6.5 * M,
  "CHEVROLET|NEXIA": 6.5 * M,
  "CHEVROLET|SPARK": 5.5 * M,
  "CHEVROLET|ONIX": 7.5 * M,
  "CHEVROLET|MONZA": 8.5 * M,
  "CHEVROLET|MALIBU": 13 * M,
  "CHEVROLET|TRACKER": 9.5 * M,
  "CHEVROLET|CAPTIVA": 12 * M,
  "CHEVROLET|EQUINOX": 14 * M,
  "CHEVROLET|TRAILBLAZER": 15 * M,
  "CHEVROLET|TRAVERSE": 25 * M,
  "CHEVROLET|TAHOE": 45 * M,
  "CHEVROLET|DAMAS": 4.5 * M,
  "CHEVROLET|LABO": 4.5 * M,
  "CHEVROLET|NIVA": 7.5 * M,
  "RAVON|NEXIA": 6 * M,
  "RAVON|R2": 5 * M,
  "RAVON|R4": 6 * M,
  "DAEWOO|GENTRA": 6 * M,
  "DAEWOO|MATIZ": 4 * M,
  // Lada / UAZ / GAZ
  "LADA|GRANTA": 5.5 * M,
  "LADA|VESTA": 7.5 * M,
  "LADA|LARGUS": 8 * M,
  "LADA|XRAY": 7 * M,
  "LADA|X-RAY": 7 * M,
  "LADA|NIVA": 7 * M,
  "LADA|4X4": 6.5 * M,
  "LADA|LEGEND": 6.5 * M,
  "UAZ|PATRIOT": 11 * M,
  "UAZ|HUNTER": 8.5 * M,
  "UAZ|PROFI": 10 * M,
  "GAZELLE|NEXT": 14 * M,
  // Chinese brands
  "CHANGAN|ALSVIN": 6.5 * M,
  "CHANGAN|EADO": 8 * M,
  "CHANGAN|CS35": 8.5 * M,
  "CHANGAN|CS55": 11 * M,
  "CHANGAN|CS75": 13 * M,
  "CHANGAN|CS85": 15 * M,
  "CHANGAN|CS95": 18 * M,
  "CHANGAN|UNI-K": 16 * M,
  "CHANGAN|UNI-V": 12.5 * M,
  "CHANGAN|UNI-T": 12 * M,
  "CHANGAN|UNI-S": 14 * M,
  "CHANGAN|HUNTER": 14 * M,
  "CHANGAN|X5": 10 * M,
  "CHANGAN|LAMORE": 10 * M,
  "GEELY|EMGRAND": 8.5 * M,
  "GEELY|COOLRAY": 10.5 * M,
  "GEELY|ATLAS": 14 * M,
  "GEELY|TUGELLA": 17 * M,
  "GEELY|MONJARO": 18 * M,
  "GEELY|OKAVANGO": 14 * M,
  "GEELY|PREFACE": 13 * M,
  "GEELY|GALAXY": 15 * M,
  "GEELY|GEOMETRY": 11 * M,
  "CHERY|TIGGO": 11 * M,
  "CHERY|ARIZZO": 8.5 * M,
  "HAVAL|JOLION": 10 * M,
  "HAVAL|F7": 13 * M,
  "HAVAL|H6": 14 * M,
  "HAVAL|DARGO": 15 * M,
  "HAVAL|M6": 10 * M,
  "HAVAL|H9": 20 * M,
  "GREAT WALL|WINGLE": 12 * M,
  "GREAT WALL|POER": 16 * M,
  "JAC|J7": 8.5 * M,
  "JAC|JS4": 10 * M,
  "JAC|JS6": 12 * M,
  "JAC|JS8": 14 * M,
  "JAC|S3": 8.5 * M,
  "JAC|T6": 11 * M,
  "JAC|T8": 13 * M,
  "JAC|T9": 16 * M,
  "JAC|N120": 20 * M,
  "JAC|N35": 10 * M,
  "JAC|N56": 13 * M,
  "JAC|N90": 18 * M,
  "JETOUR|DASHING": 14 * M,
  "JETOUR|X70PLUS": 13 * M,
  "JETOUR|X90PLUS": 16 * M,
  "JETOUR|T2": 22 * M,
  "EXEED|LX": 13 * M,
  "EXEED|TXL": 16 * M,
  "EXEED|VX": 20 * M,
  "OMODA|C5": 10.5 * M,
  "OMODA|S5": 8.5 * M,
  "JAECOO|J7": 13 * M,
  "JAECOO|J8": 18 * M,
  "BYD|SONG": 15 * M,
  "BYD|HAN": 20 * M,
  "BYD|TANG": 25 * M,
  "BYD|QIN": 11 * M,
  "BYD|SEAL": 18 * M,
  "BYD|YUAN": 12 * M,
  "BYD|ATTO": 12 * M,
  "BYD|CHAZOR": 12 * M,
  "ZEEKR|001": 27 * M,
  "ZEEKR|009": 38 * M,
  "ZEEKR|7X": 24 * M,
  "ZEEKR|X": 17 * M,
  "LI|L6": 26 * M,
  "LI|L7": 30 * M,
  "LI|L9": 38 * M,
  "TANK|300": 22 * M,
  "TANK|500": 30 * M,
  "TANK|700": 45 * M,
  "HONGQI|H5": 13 * M,
  "HONGQI|H9": 30 * M,
  "HONGQI|HS5": 18 * M,
  "HONGQI|E-HS9": 40 * M,
  // European, Japanese, premium
  "VOLKSWAGEN|POLO": 9 * M,
  "VOLKSWAGEN|JETTA": 11 * M,
  "VOLKSWAGEN|PASSAT": 16 * M,
  "VOLKSWAGEN|TIGUAN": 18 * M,
  "VOLKSWAGEN|TERAMONT": 25 * M,
  "VOLKSWAGEN|TOUAREG": 40 * M,
  "VOLKSWAGEN|ID.4": 15 * M,
  "VOLKSWAGEN|ID.6": 18 * M,
  "VOLKSWAGEN|ID6": 18 * M,
  "VOLKSWAGEN|MULTIVAN": 35 * M,
  "VOLKSWAGEN|TRANSPORTER": 25 * M,
  "VOLKSWAGEN|CRAFTER": 30 * M,
  "VOLKSWAGEN|AMAROK": 25 * M,
  "SKODA|RAPID": 9 * M,
  "SKODA|OCTAVIA": 12 * M,
  "SKODA|KODIAQ": 18 * M,
  "SKODA|SUPERB": 17 * M,
  "RENAULT|LOGAN": 7 * M,
  "RENAULT|SANDERO": 7.5 * M,
  "RENAULT|DUSTER": 9.5 * M,
  "RENAULT|ARKANA": 11 * M,
  "RENAULT|KAPTUR": 10 * M,
  "NISSAN|ALMERA": 8 * M,
  "NISSAN|QASHQAI": 14 * M,
  "NISSAN|X-TRAIL": 17 * M,
  "NISSAN|MURANO": 22 * M,
  "NISSAN|PATROL": 45 * M,
  "MITSUBISHI|ASX": 12 * M,
  "MITSUBISHI|OUTLANDER": 17 * M,
  "MITSUBISHI|PAJERO": 22 * M,
  "MITSUBISHI|L200": 17 * M,
  "MITSUBISHI|XPANDER": 11 * M,
  "MAZDA|CX-5": 16 * M,
  "MAZDA|6": 15 * M,
  "HONDA|CR-V": 18 * M,
  "SUBARU|FORESTER": 18 * M,
  "SUBARU|OUTBACK": 20 * M,
  "LEXUS|ES250": 30 * M,
  "LEXUS|ES350": 34 * M,
  "LEXUS|NX200": 30 * M,
  "LEXUS|RX": 40 * M,
  "LEXUS|GX550": 55 * M,
  "LEXUS|LX600": 75 * M,
  "LEXUS|LX": 75 * M,
  "BMW|320I": 26 * M,
  "BMW|330I": 30 * M,
  "BMW|520I": 32 * M,
  "BMW|530I": 36 * M,
  "BMW|740I": 60 * M,
  "BMW|X1": 25 * M,
  "BMW|X3": 32 * M,
  "BMW|X5": 48 * M,
  "BMW|X6": 55 * M,
  "BMW|X7": 65 * M,
  "MERCEDES-BENZ|C": 28 * M,
  "MERCEDES-BENZ|E": 38 * M,
  "MERCEDES-BENZ|S": 70 * M,
  "MERCEDES-BENZ|GLC": 35 * M,
  "MERCEDES-BENZ|GLE": 50 * M,
  "MERCEDES-BENZ|GLS": 65 * M,
  "MERCEDES-BENZ|G": 90 * M,
  "MERCEDES-BENZ|SPRINTER": 30 * M,
  "MERCEDES-BENZ|V-CLASS": 45 * M,
  "AUDI|A4": 25 * M,
  "AUDI|A6": 32 * M,
  "AUDI|Q5": 32 * M,
  "AUDI|Q7": 45 * M,
  "AUDI|Q8": 55 * M,
  "PORSCHE|MACAN": 45 * M,
  "PORSCHE|CAYENNE": 65 * M,
  "LAND ROVER|RANGE": 75 * M,
  "LAND ROVER|DEFENDER": 50 * M,
  "LAND ROVER|DISCOVERY": 45 * M,
  "RANGE|ROVER": 75 * M,
  "TESLA|MODEL": 22 * M,
  "CADILLAC|ESCALADE": 60 * M,
  "GENESIS|G80": 30 * M,
  "GENESIS|GV80": 38 * M,
  "INFINITI|QX80": 50 * M,
};

/** Базовая цена марки — когда модели нет в списке выше. */
export const BRAND_PRESETS: Record<string, number> = {
  TOYOTA: 18 * M,
  HYUNDAI: 13 * M,
  KIA: 12 * M,
  BMW: 35 * M,
  CHANGAN: 11 * M,
  JAC: 10 * M,
  ГАЗ: 14 * M,
  GAZELLE: 14 * M,
  GEELY: 12 * M,
  VOLKSWAGEN: 15 * M,
  CHEVROLET: 9 * M,
  "MERCEDES-BENZ": 40 * M,
  LADA: 6.5 * M,
  UAZ: 10 * M,
  NISSAN: 14 * M,
  AUDI: 32 * M,
  "GREAT WALL": 13 * M,
  LEXUS: 38 * M,
  BYD: 15 * M,
  RENAULT: 9 * M,
  MITSUBISHI: 15 * M,
  HONGQI: 20 * M,
  JETOUR: 14 * M,
  DONGFENG: 10 * M,
  FORD: 18 * M,
  HAVAL: 13 * M,
  HONDA: 17 * M,
  INFINITI: 30 * M,
  JAGUAR: 40 * M,
  AVATR: 25 * M,
  CHERY: 10 * M,
  LIFAN: 6 * M,
  SUBARU: 18 * M,
  ZEEKR: 25 * M,
  FAW: 9 * M,
  "FAW BESTUNE": 11 * M,
  MAZDA: 15 * M,
  PORSCHE: 60 * M,
  SKODA: 13 * M,
  CADILLAC: 40 * M,
  DEEPAL: 16 * M,
  EXEED: 16 * M,
  GENESIS: 30 * M,
  KAIYI: 7.5 * M,
  "LAND ROVER": 55 * M,
  RANGE: 75 * M,
  MINI: 22 * M,
  OMODA: 10 * M,
  SUZUKI: 9 * M,
  ACURA: 25 * M,
  AITO: 28 * M,
  FOTON: 12 * M,
  LI: 28 * M,
  PEUGEOT: 13 * M,
  RAVON: 5.5 * M,
  SSANGYONG: 13 * M,
  TANK: 25 * M,
  BENTLEY: 150 * M,
  DAEWOO: 5 * M,
  GAC: 14 * M,
  JAECOO: 13 * M,
  LABO: 4.5 * M,
  MG: 10 * M,
  ROX: 25 * M,
  TESLA: 22 * M,
  BAIC: 15 * M,
  BAW: 8 * M,
  FORLAND: 10 * M,
  IM: 22 * M,
  JETTA: 9 * M,
  SAMAT: 8 * M,
  VOYAH: 28 * M,
};

/** Цена по умолчанию, если неизвестна даже марка. */
export const DEFAULT_PRESET = 12 * M;

export interface PricePreset {
  price: number;
  /** model — цена конкретной модели, brand — типичная для марки, default — общая. */
  level: "model" | "brand" | "default";
}

export function pricePreset(model: Pick<LeaseModel, "brand" | "name">): PricePreset {
  const brand = model.brand.trim().toUpperCase();
  let name = model.name.trim().toUpperCase();
  if (name.startsWith(`${brand} `)) name = name.slice(brand.length).trim();
  const first = name.split(/\s+/)[0] ?? "";
  const byModel = MODEL_PRESETS[`${brand}|${first}`];
  if (byModel) return { price: byModel, level: "model" };
  const byBrand = BRAND_PRESETS[brand];
  if (byBrand) return { price: byBrand, level: "brand" };
  return { price: DEFAULT_PRESET, level: "default" };
}
