/** Synthetic hackathon fixtures, in millions of KZT. These are NOT market quotations. */
export const PRICE_RULES_VERSION = "synthetic-demo-v2-bounded";
export const PRICE_ESTIMATED_AT = "2026-09-25";

type Rule = readonly [pattern: string, millions: number, family: string];

/** More specific variants precede broad model families. No seller premiums are invented. */
export const MODEL_PRICE_RULES: Record<string, readonly Rule[]> = {
  ACURA: [
    ["^MDX", 28, "MDX"],
    ["^RDX", 22, "RDX"],
    ["^TSX", 10, "TSX"],
  ],
  AITO: [
    ["^M9", 42, "M9"],
    ["^M7", 28, "M7"],
    ["^M5", 22, "M5"],
  ],
  AUDI: [
    ["^R8", 70, "R8"],
    ["^Q8", 48, "Q8"],
    ["^(A )?Q7", 40, "Q7"],
    ["^Q6", 35, "Q6"],
    ["^Q5", 29, "Q5"],
    ["^Q3", 22, "Q3"],
    ["^Q2", 17, "Q2"],
    ["^A8", 46, "A8"],
    ["^A7", 35, "A7"],
    ["^A6", 29, "A6"],
    ["^A5", 25, "A5"],
    ["^A4", 21, "A4"],
    ["^A3", 17, "A3"],
    ["E-TRON", 30, "e-tron"],
  ],
  AVATR: [
    ["^(012|12)$", 30, "12"],
    ["^(011|11)$", 28, "11"],
    ["^07$", 24, "07"],
    ["^06$", 22, "06"],
  ],
  BAIC: [["^BJ40", 16, "BJ40"]],
  BAW: [["6521", 8, "коммерческий BAW"]],
  BENTLEY: [
    ["FLYING SPUR", 110, "Flying Spur"],
    ["GT", 120, "Continental GT"],
  ],
  BMW: [
    ["^X7", 65, "X7"],
    ["^X6 M", 70, "X6 M"],
    ["^X6", 52, "X6"],
    ["^X5 M", 66, "X5 M"],
    ["^X5", 45, "X5"],
    ["^X4 M", 42, "X4 M"],
    ["^X4", 33, "X4"],
    ["^X3 M", 39, "X3 M"],
    ["^X3", 30, "X3"],
    ["^X2", 25, "X2"],
    ["^X1", 22, "X1"],
    ["^M8|^M850", 80, "M8"],
    ["^M5", 58, "M5"],
    ["^M4", 38, "M4"],
    ["^M2", 30, "M2"],
    ["^IX", 55, "iX"],
    ["^I3", 18, "i3"],
    ["^8", 60, "8 Series"],
    ["^7", 55, "7 Series"],
    ["^6", 34, "6 Series"],
    ["^5", 30, "5 Series"],
    ["^4", 27, "4 Series"],
    ["^3", 23, "3 Series"],
    ["^2", 19, "2 Series"],
    ["^Z4", 35, "Z4"],
  ],
  BYD: [
    ["^TANG|^ATTO 8", 24, "крупный SUV"],
    ["^HAN", 21, "Han"],
    ["^SEALION", 22, "Sealion"],
    ["^SEAL [56]", 13, "Seal 5/6"],
    ["^SEAL", 19, "Seal"],
    ["^SONG", 16, "Song"],
    ["^YUAN", 12, "Yuan"],
    ["^QIN|DESTROYER|CHAZOR", 11, "компактный седан"],
    ["^E2", 9, "E2"],
  ],
  CADILLAC: [
    ["ESCALADE ESV", 70, "Escalade ESV"],
    ["ESCALADE", 60, "Escalade"],
    ["XT6", 30, "XT6"],
    ["XT5", 24, "XT5"],
    ["XT4", 20, "XT4"],
  ],
  CHANGAN: [
    ["CS95", 18, "CS95"],
    ["CS85|UNI-K", 16, "крупный кроссовер"],
    ["CS75|UNI-Z|Q05|Q07|OSHAN Z6|X7 PLUS", 13, "средний кроссовер"],
    ["CS55|UNI-T|OSHAN X5|X5 PLUS", 11, "компактный кроссовер"],
    ["CS35", 9, "CS35"],
    ["HUNTER|LANTOP|F70|EXPLORER", 14, "пикап"],
    ["A07|UNI-R", 15, "старший седан"],
    ["A05|A06|UNI-V|LAMORE|YIDA|EADO PLUS", 10, "современный седан"],
    ["BENBEN|BENNI|LUMIN|CS15|CX20", 5.5, "малый автомобиль"],
    ["ALSVIN|EADO|RAETON", 7.5, "седан"],
    ["EM80|CM8|A600|RUixing|UNO|SC6350|CROSS STAR", 8, "минивэн/коммерческий"],
  ],
  CHERY: [
    ["TIGGO 9", 15, "Tiggo 9"],
    ["TIGGO 8 PRO MAX", 14, "Tiggo 8 Pro Max"],
    ["TIGGO 8 PRO", 12.5, "Tiggo 8 Pro"],
    ["TIGGO 8|^C8", 11.5, "Tiggo 8"],
    ["TIGGO 7 PRO MAX", 12, "Tiggo 7 Pro Max"],
    ["TIGGO 7", 10, "Tiggo 7"],
    ["TIGGO [45]", 8, "Tiggo 4/5"],
    ["TIGGO [23]|^2 PRO", 6.5, "Tiggo 2/3"],
    ["ARR?IZZO 8", 11, "Arrizo 8"],
    ["ARR?IZZO 6", 8, "Arrizo 6"],
  ],
  CHEVROLET: [
    ["TAHOE", 45, "Tahoe"],
    ["CAMARO", 25, "Camaro"],
    ["TRAVERSE", 25, "Traverse"],
    ["TRAILBLAZER", 18, "Trailblazer"],
    ["EQUINOX", 17, "Equinox"],
    ["MALIBU", 14, "Malibu"],
    ["CAPTIVA", 12, "Captiva"],
    ["TRACKER", 10.5, "Tracker"],
    ["ONIX", 7, "Onix"],
    ["COBALT", 6.5, "Cobalt"],
    ["CRUZE|ORLANDO|MENLO|MONZA", 8, "средний легковой"],
    ["DAMAS|LABO", 5, "малый коммерческий"],
    ["AVEO|NEXIA|SPARK|LACETTI|NIVA", 5.5, "бюджетный легковой"],
  ],
  DAEWOO: [
    ["MATIZ", 2.5, "Matiz"],
    ["GENTRA", 5.5, "Gentra"],
  ],
  DEEPAL: [
    ["S09", 27, "S09"],
    ["G318", 22, "G318"],
    ["S07", 18, "S07"],
    ["S05", 15, "S05"],
  ],
  DONGFENG: [
    ["FENGON|^580", 10, "Fengon"],
    ["NANO", 5, "малый электромобиль"],
    ["CAPTAIN|Z80", 12, "коммерческий"],
    ["DFSK|Z55", 7.5, "малый коммерческий"],
  ],
  EXEED: [
    ["VX", 23, "VX"],
    ["TXL", 17, "TXL"],
    ["LX", 13, "LX"],
  ],
  FAW: [
    ["T77|X80", 11, "T77/X80"],
    ["X40", 8, "X40"],
    ["T80", 9, "T80"],
    ["^CA", 7, "коммерческий FAW"],
  ],
  "FAW BESTUNE": [["T77", 11, "T77"]],
  FORD: [
    ["EXPLORER", 27, "Explorer"],
    ["TOURNEO", 18, "Tourneo"],
    ["KUGA", 13, "Kuga"],
    ["MONDEO", 11, "Mondeo"],
    ["ECOSPORT", 9, "EcoSport"],
    ["FOCUS", 8, "Focus"],
    ["FIESTA", 6, "Fiesta"],
  ],
  FORLAND: [["K2", 9, "K2"]],
  FOTON: [
    ["TUNLAND", 15, "Tunland"],
    ["BJ5030", 11, "коммерческий фургон"],
    ["XIANGLING", 8, "Xiangling"],
  ],
  GAC: [
    ["M8", 25, "M8"],
    ["GS5", 12, "GS5"],
  ],
  GAZELLE: [["NEXT", 12, "Next"]],
  GEELY: [
    ["MONJARO|GALAXY M9", 20, "крупный кроссовер"],
    ["TUGELLA|OKAVANGO", 17, "старший кроссовер"],
    ["ATLAS|AZKARRA|GALAXY L7|STARSHIP 7|EX5", 14, "средний кроссовер"],
    ["COOLRAY|BINYUE|CITYRAY|BOYUE|ICON", 11, "компактный кроссовер"],
    ["GALAXY E8|PREFACE", 15, "старший седан"],
    ["GALAXY|GEOMETRY|GEOME|BINRUI|EMGRAND L", 10, "новое семейство"],
    ["JIAJI|FARIZON", 12, "минивэн/пикап"],
    ["EMGRAND|GC9|VISION X6", 8, "Emgrand/средний"],
    ["VISION X3|GC6|GC7|SC7|^MK|^CK|^FC|BEAUTY", 5, "раннее компактное семейство"],
  ],
  GENESIS: [
    ["GV80", 40, "GV80"],
    ["GV70", 30, "GV70"],
    ["G80", 30, "G80"],
    ["G70", 24, "G70"],
  ],
  "GREAT WALL": [
    ["POER", 15, "Poer"],
    ["WINGLE 7", 12, "Wingle 7"],
    ["WINGLE", 9, "Wingle"],
    ["HOVER H[56]", 8, "Hover H5/H6"],
    ["HOVER|SAFE|PEGASUS|SING", 6, "ранний SUV"],
    ["DEER|SAILOR", 5.5, "ранний пикап"],
    ["COWRY", 5, "Cowry"],
    ["FLORID|PERI|COOLBEAR|VOLEEX", 4, "ранний легковой"],
  ],
  HAVAL: [
    ["H9", 23, "H9"],
    ["H5|DARGO", 16, "крупный SUV"],
    ["H6|F7", 13, "средний SUV"],
    ["JOLION", 10, "Jolion"],
    ["M6", 8.5, "M6"],
  ],
  HONDA: [
    ["CR-V", 20, "CR-V"],
    ["ODYSSEY", 22, "Odyssey"],
    ["HR-V", 14, "HR-V"],
    ["NS1|NP1", 15, "электрическое семейство"],
    ["INSIGHT", 10, "Insight"],
  ],
  HONGQI: [
    ["E-HS9", 40, "E-HS9"],
    ["H9|HS7", 30, "старшее семейство"],
    ["H6|H7|HS5", 22, "среднее семейство"],
    ["H5|E-QM5|E-HS3", 17, "младшее семейство"],
  ],
  HYUNDAI: [
    ["PALISADE", 29, "Palisade"],
    ["STARIA|NEXO", 23, "Staria/Nexo"],
    ["SANTA FE|SANTA CRUZ", 20, "Santa Fe/Cruz"],
    ["TUCSON", 13.5, "Tucson"],
    ["MUFASA|CUSTIN|CUSTO", 13, "Mufasa/Custin"],
    ["SONATA", 14, "Sonata"],
    ["ELANTRA|AVANTE", 10.5, "Elantra/Avante"],
    ["GRANDEUR|AZERA|ASLAN|GENESIS|EQUUS|CENTENNIAL", 18, "представительское семейство"],
    ["CRETA|KONA|IX25|VENUE|BAYON", 10, "компактный кроссовер"],
    ["IONIQ", 15, "Ioniq"],
    ["H.?350", 18, "H350"],
    ["PORTER|H.?100", 12, "малый грузовой"],
    ["STAREX|H.?1|ENTOURAGE", 13, "минивэн"],
    ["ACCENT|SOLARIS|VERNA|LAFESTA|MISTRA", 8, "компактный седан"],
    ["I30|I40|VELOSTER|IX35", 9, "средний легковой"],
    ["I10|I20|CASPER", 7, "малый автомобиль"],
    ["IX55|VERACRUZ|MAXCRUZ", 12, "ранний крупный SUV"],
    ["TERRACAN|GALLOPER", 7, "ранний внедорожник"],
    ["COUPE|TIBURON|TUSCANI|S-COUPE", 7, "купе"],
    [
      "GETZ|CLICK|ATOS|EON|EXCEL|PONY|LANTRA|MARCIA|DYNASTY|LAVITA|MATRIX|TRAJET|SANTAMO|GRACE|IX20|^XG",
      4.5,
      "раннее модельное семейство",
    ],
  ],
  IM: [["LS7", 27, "LS7"]],
  INFINITI: [
    ["QX80", 40, "QX80"],
    ["QX60|JX", 24, "семейный SUV"],
    ["QX55", 25, "QX55"],
    ["QX50", 20, "QX50"],
    ["Q50", 16, "Q50"],
    ["Q30", 12, "Q30"],
  ],
  JAC: [
    ["T9", 18, "T9"],
    ["T8", 13, "T8"],
    ["T6|HFC", 10, "пикап"],
    ["N120", 20, "N120"],
    ["N90", 16, "N90"],
    ["N56", 13, "N56"],
    ["N35", 10, "N35"],
    ["SUNRAY", 15, "Sunray"],
    ["JS8|X8|^S7", 13, "крупный кроссовер"],
    ["JS6|^S5", 11, "средний кроссовер"],
    ["JS[345]|^S[34]|IEV|E-JS4", 9, "компактный кроссовер"],
    ["^J7|E-J7|A5 PLUS", 9, "седан J7"],
    ["^M[345]", 11, "минивэн"],
    ["^M1|^J[2356]|^S[12]|YTTRIUM", 6, "малый легковой"],
  ],
  JAECOO: [
    ["J8", 20, "J8"],
    ["J7", 14, "J7"],
  ],
  JAGUAR: [
    ["F-TYPE|^SV", 40, "спорткар"],
    ["I-PACE", 30, "I-Pace"],
    ["F-PACE", 28, "F-Pace"],
    ["E-PACE", 22, "E-Pace"],
    ["^XJ", 30, "XJ"],
    ["^XE", 18, "XE"],
  ],
  JETOUR: [
    ["T2", 18, "T2"],
    ["T1", 15, "T1"],
    ["X90", 14, "X90"],
    ["DASHING", 12, "Dashing"],
    ["X70", 11, "X70"],
    ["X50", 8, "X50"],
  ],
  JETTA: [["VS5", 10, "VS5"]],
  KAIYI: [
    ["X7", 13, "X7"],
    ["X3 PRO", 9, "X3 Pro"],
    ["X3", 8, "X3"],
    ["XUANJIE", 9, "электрическое семейство"],
    ["E5", 7.5, "E5"],
  ],
  KIA: [
    ["EV9", 40, "EV9"],
    ["EV6", 28, "EV6"],
    ["EV5", 23, "EV5"],
    ["K9|K900|QUORIS", 36, "представительский седан"],
    ["TELLURIDE|MOHAVE", 26, "крупный SUV"],
    ["CARNIVAL|SEDONA", 23, "минивэн"],
    ["SORENTO", 20, "Sorento"],
    ["SPORTAGE", 13, "Sportage"],
    ["SELTOS", 12.5, "Seltos"],
    ["K8", 23, "K8"],
    ["K7|CADENZA|STINGER", 18, "старший седан"],
    ["K5|OPTIMA", 14, "K5/Optima"],
    ["K4|K3|CERATO|FORTE|CEED|XCEED|PROCEED", 10, "средний легковой"],
    ["SOUL|NIRO|KX5", 11, "компактное семейство"],
    ["RIO|SOLUTO|PEGAS|SONET|STONIC|KX1", 7.5, "малый легковой"],
    ["PICANTO|MORNING|RAY", 6, "городской автомобиль"],
    ["BONGO|K-2500|K-4000", 12, "коммерческий"],
    ["CARENS|JOICE|PREGIO|BESTA|CARSTAR|VENGA", 7, "ранний минивэн"],
    [
      "AVELLA|CAPITAL|CLARUS|CONCORD|CREDOS|ELAN$|ENTERPRISE|LOTZE|MAGENTIS|OPIRUS|POTENTIA|PRIDE|RETONA|ROCSTA|SEPHIA|SHUMA|SPECTRA|TOPIC|VISTO|X-TREK",
      4.5,
      "раннее модельное семейство",
    ],
  ],
  LABO: [["LABO|B100", 5, "малый коммерческий (марка требует проверки)"]],
  LADA: [
    ["VESTA SW CROSS", 9, "Vesta SW Cross"],
    ["VESTA SW", 8.5, "Vesta SW"],
    ["VESTA", 8, "Vesta"],
    ["LARGUS", 8, "Largus"],
    ["NIVA TRAVEL", 8, "Niva Travel"],
    ["NIVA|212|213|4X4|4[*]4|LEGEND", 6.5, "Niva/4x4"],
    ["GRANTA", 6, "Granta"],
    ["XRAY|X-RAY", 7, "XRAY"],
    ["KALINA", 4, "Kalina"],
  ],
  "LAND ROVER": [
    ["NX 300", 20, "неоднозначная запись справочника"],
    ["RANGE ROVER SPORT", 50, "Range Rover Sport"],
    ["RANGE ROVER VELAR", 38, "Velar"],
    ["RANGE ROVER EVOQUE", 28, "Evoque"],
    ["RANGE ROVER", 65, "Range Rover"],
    ["DEFENDER", 48, "Defender"],
    ["DISCOVERY", 30, "Discovery Sport"],
  ],
  LEXUS: [
    ["LX600", 70, "LX600"],
    ["LX 570", 45, "LX570"],
    ["GX550", 55, "GX550"],
    ["GX 460", 35, "GX460"],
    ["RX", 30, "RX"],
    ["NX", 24, "NX"],
    ["UX", 19, "UX"],
    ["ES", 25, "ES"],
    ["GS", 20, "GS"],
    ["IS", 15, "IS"],
  ],
  LI: [
    ["L9", 35, "L9"],
    ["L7", 28, "L7"],
    ["L6 MAX", 26, "L6 Max"],
    ["L6", 24, "L6"],
  ],
  LIFAN: [
    ["X70", 7, "X70"],
    ["X60|MYWAY", 6, "средний SUV"],
    ["X50|MURMAN", 5.5, "младшее семейство"],
    ["SOLANO", 4.5, "Solano"],
  ],
  MAZDA: [
    ["CX9", 24, "CX-9"],
    ["CX-5", 18, "CX-5"],
    ["CX30", 16, "CX-30"],
    ["^6$", 15, "Mazda6"],
    ["^3$", 12, "Mazda3"],
  ],
  "MERCEDES-BENZ": [
    ["G63|G 5", 95, "G-Class AMG"],
    ["^GLS", 60, "GLS"],
    ["^GLE 53", 60, "GLE AMG"],
    ["^GLE", 45, "GLE"],
    ["^S ", 65, "S-Class"],
    ["V-CLASS", 42, "V-Class"],
    ["SPRINTER", 28, "Sprinter"],
    ["^GLC", 32, "GLC"],
    ["^GLK", 18, "GLK"],
    ["^GLA", 24, "GLA"],
    ["^E", 30, "E-Class"],
    ["C 43", 35, "C-Class AMG"],
    ["^C|^С", 23, "C-Class/CLA"],
    ["A 35", 28, "A-Class AMG"],
    ["^A", 20, "A-Class"],
    ["^350", 26, "неуточнённая серия 350"],
  ],
  MG: [
    ["HS", 12, "HS"],
    ["^5$", 8, "MG5"],
  ],
  MINI: [
    ["COUNTRYMAN", 20, "Countryman"],
    ["CLUBMAN", 16, "Clubman"],
    ["COOPER|HATCH", 14, "Cooper"],
  ],
  MITSUBISHI: [
    ["PAJERO SPORT|MONTERO SPORT", 22, "Pajero Sport"],
    ["PAJERO", 18, "Pajero"],
    ["OUTLANDER", 17, "Outlander"],
    ["L.?200", 18, "L200"],
    ["XPANDER", 12, "Xpander"],
    ["ECLIPSE CROSS", 14, "Eclipse Cross"],
    ["ASX|^CROSS", 11, "ASX"],
    ["LANCER|ECLIPSE", 8, "легковой"],
  ],
  NISSAN: [
    ["PATROL", 42, "Patrol"],
    ["MURANO", 20, "Murano"],
    ["X-TRAIL|ROGUE", 17, "X-Trail/Rogue"],
    ["QASHQAI", 14, "Qashqai"],
    ["X-TERRA|QUEST", 18, "крупное семейство"],
    ["ALTIMA|TEANA", 12, "средний седан"],
    ["TERRANO|JUKE", 10, "компактный SUV"],
    ["SENTRA", 9, "Sentra"],
    ["ALMERA|NOTE|T[IY]L?DA|TIIDA", 6, "малый легковой"],
  ],
  OMODA: [
    ["C7", 15, "C7"],
    ["C5", 11, "C5"],
    ["S5", 8, "S5"],
  ],
  PEUGEOT: [
    ["408", 10, "408"],
    ["308", 8, "308"],
    ["301", 6, "301"],
  ],
  PORSCHE: [
    ["911", 90, "911"],
    ["CAYENNE COUPE", 65, "Cayenne Coupe"],
    ["CAYENNE", 58, "Cayenne"],
    ["PANAMERA", 60, "Panamera"],
    ["TAYCAN", 55, "Taycan"],
    ["MACAN S", 40, "Macan S"],
    ["MACAN", 35, "Macan"],
  ],
  RANGE: [
    ["SPORT", 50, "неуточнённая Range Rover Sport"],
    ["ROVER", 65, "неуточнённая Range Rover"],
  ],
  RAVON: [
    ["R4", 5.5, "R4"],
    ["R3", 5, "R3"],
    ["R2", 4.5, "R2"],
  ],
  RENAULT: [
    ["MASTER", 18, "Master"],
    ["KOLEOS|QM6", 14, "средний SUV"],
    ["ARKANA", 12, "Arkana"],
    ["DUSTER|KAPTUR|CAPTUR", 10, "компактный SUV"],
    ["SAMSUNG", 11, "SM6"],
    ["DOKKER", 8, "Dokker"],
    ["LOGAN|SANDERO", 6, "малый легковой"],
  ],
  ROX: [
    ["ADAMAS", 40, "Adamas"],
    ["01", 32, "01"],
  ],
  SAMAT: [["SUPER", 10, "неоднозначная запись; условный учебный бюджет"]],
  SKODA: [
    ["KODIAQ", 20, "Kodiaq"],
    ["SUPERB B6", 10, "ранний Superb"],
    ["SUPERB", 22, "Superb"],
    ["OCTAVIA A7", 12, "Octavia A7"],
    ["OCTAVIA", 15, "Octavia"],
    ["YETI", 9, "Yeti"],
    ["RAPID", 8, "Rapid"],
  ],
  SSANGYONG: [
    ["TIVOLI", 10, "Tivoli"],
    ["ACTYON", 8, "Actyon"],
    ["KYRON", 7, "Kyron"],
  ],
  SUBARU: [
    ["WRX", 24, "WRX"],
    ["OUTBACK", 22, "Outback"],
    ["FORESTER", 20, "Forester"],
    ["CROSSTRECK", 17, "Crosstrek"],
    ["XV", 14, "XV"],
    ["LEGACY", 12, "Legacy"],
  ],
  SUZUKI: [
    ["GRAND VITARA", 14, "Grand Vitara"],
    ["SX4", 10, "SX4"],
    ["ERTIGA", 9, "Ertiga"],
    ["BALENO", 8, "Baleno"],
  ],
  TANK: [
    ["700", 45, "700"],
    ["500", 32, "500"],
    ["300", 22, "300"],
  ],
  TESLA: [
    ["MODEL 3", 22, "Model 3"],
    ["MODEL Y|^Y$", 26, "Model Y"],
  ],
  TOYOTA: [
    ["LC300", 55, "Land Cruiser 300"],
    ["LAND CRUISER.*PRADO|LC 150PRADO", 32, "Prado"],
    ["LAND CRUISER", 48, "Land Cruiser"],
    ["MEGA CRUISER", 40, "Mega Cruiser"],
    ["CENTURY", 70, "Century"],
    ["GRAND HIGHLANDER", 36, "Grand Highlander"],
    ["HIGHLANDER|CROWN KLUGER", 30, "Highlander"],
    ["ALPHARD|VELLFIRE", 38, "Alphard/Vellfire"],
    ["SIENNA|GRANVIA", 28, "крупный минивэн"],
    ["4RUNNER|FJ CRUISER", 28, "рамный SUV"],
    ["FORTUNER|HILUX", 24, "внедорожник/пикап"],
    ["HARRIER|VENZA", 22, "средний кроссовер"],
    ["RAV4", 21, "RAV4"],
    ["COROLLA CROSS|FRONTLANDER", 16, "Corolla Cross"],
    ["CAMRY GRACIA|CAMRY PROMINENT", 5, "ранняя Camry"],
    ["CAMRY", 20, "Camry"],
    ["CROWN MAJESTA", 18, "Crown Majesta"],
    ["CROWN|AVALON", 22, "старший седан"],
    ["COROLLA (II|CERES|LEVIN|RUMION|VERSO)", 6, "ранняя Corolla"],
    ["COROLLA|LEVIN", 12, "Corolla/Levin"],
    ["BZ 4X|BZ3|MIRAI", 18, "электрифицированное семейство"],
    ["C-HR|IZOA", 15, "городской кроссовер"],
    ["GR86|GT 86", 17, "купе 86"],
    ["HIACE|LITE ACE|PICK-UP", 16, "коммерческий"],
    ["PRIUS", 13, "Prius"],
    ["AQUA|RUSH", 10, "малый современный"],
    ["NOAH|ESQUIRE|INNOVA|VOXY", 18, "средний минивэн"],
    ["ESTIMA|PREVIA|VERSO|MARK X ZIO", 11, "семейный минивэн"],
    ["MARK X|PREMIO|ALLION|AVENSIS|AURION|AURIS", 10, "средний легковой"],
    ["MARK II|CHASER|CRESTA|ARISTO|ALTEZZA|CELSIOR|BREVIS|BLADE", 7, "ранний старший легковой"],
    ["CELICA|MR2|MR-S", 9, "раннее купе"],
    ["PASSO|PORTE|PIXIS|AGYA|AYGO|BELTA|ECHO|PLATZ|DUET|CORSA|IST", 6, "малый автомобиль"],
    ["CAMI|BLIZZARD|HILUX SURF|KLUGER", 9, "ранний SUV"],
    [
      "GAIA|IPSUM|ISIS|NADIA|OPA|PICNIC|MODEL F|MASTER|GRAND HIACE|FUN CARGO|AVANZA",
      6.5,
      "ранний семейный",
    ],
    [
      "ALLEX|CALDINA|CARINA|CORONA|CAVALIER|CRESSIDA|CURREN|CYNOS|MATRIX|PASEO",
      5,
      "ранний легковой",
    ],
  ],
  UAZ: [
    ["PATRIOT|3163", 12, "Patriot"],
    ["PROFI|236", 11, "Profi"],
    ["HUNTER", 9, "Hunter"],
    ["220|290|292|330|362|374|390|396", 8, "коммерческий UAZ"],
  ],
  VOLKSWAGEN: [
    ["TOUAREG", 35, "Touareg"],
    ["TERAMONT", 28, "Teramont"],
    ["MULTIVAN|CARAVELLE", 25, "минивэн"],
    ["CRAFTER|AMAROK", 24, "коммерческий/пикап"],
    ["TRANSPORTER", 18, "Transporter"],
    ["ID.?6", 22, "ID.6"],
    ["ID.?4", 18, "ID.4"],
    ["TIGUAN", 20, "Tiguan"],
    ["TAOS|TACQUA", 14, "компактный SUV"],
    ["PASSAT", 16, "Passat"],
    ["GOLF|JETTA|CADDY", 12, "компактный легковой"],
    ["POLO|BORA", 8, "бюджетный легковой"],
  ],
  VOYAH: [["FREE", 26, "Free"]],
  ZEEKR: [
    ["LI L9", 35, "неоднозначная запись Li L9 в марке Zeekr"],
    ["LI L7", 28, "неоднозначная запись Li L7 в марке Zeekr"],
    ["009", 40, "009"],
    ["8X", 36, "8X"],
    ["7X", 28, "7X"],
    ["001", 26, "001"],
    ["^X", 20, "X"],
  ],
  ГАЗ: [
    ["A65|А65|A31T|A32T", 16, "коммерческий Next/NN"],
    ["A[23]|А[23]", 12, "коммерческий Next"],
    ["231|275", 9, "Соболь"],
    ["270|330", 9.5, "Газель"],
  ],
};

/** Baselines apply only when the model family is unknown, including newly added API models. */
export const BRAND_SEGMENT_BASELINES: Record<string, number> = {
  ACURA: 24,
  AITO: 28,
  AUDI: 30,
  AVATR: 27,
  BAIC: 15,
  BAW: 8,
  BENTLEY: 110,
  BMW: 35,
  BYD: 16,
  CADILLAC: 35,
  CHANGAN: 11,
  CHERY: 10,
  CHEVROLET: 10,
  DAEWOO: 4,
  DEEPAL: 20,
  DONGFENG: 9,
  EXEED: 18,
  FAW: 10,
  "FAW BESTUNE": 11,
  FORD: 14,
  FORLAND: 9,
  FOTON: 11,
  GAC: 18,
  GAZELLE: 12,
  GEELY: 12,
  GENESIS: 32,
  "GREAT WALL": 10,
  HAVAL: 13,
  HONDA: 17,
  HONGQI: 24,
  HYUNDAI: 12,
  IM: 27,
  INFINITI: 25,
  JAC: 10,
  JAECOO: 17,
  JAGUAR: 28,
  JETOUR: 13,
  JETTA: 10,
  KAIYI: 9,
  KIA: 12,
  LABO: 5,
  LADA: 7,
  "LAND ROVER": 40,
  LEXUS: 30,
  LI: 28,
  LIFAN: 5.5,
  MAZDA: 16,
  "MERCEDES-BENZ": 35,
  MG: 10,
  MINI: 17,
  MITSUBISHI: 16,
  NISSAN: 14,
  OMODA: 11,
  PEUGEOT: 8,
  PORSCHE: 55,
  RANGE: 50,
  RAVON: 5,
  RENAULT: 10,
  ROX: 34,
  SAMAT: 10,
  SKODA: 15,
  SSANGYONG: 8,
  SUBARU: 19,
  SUZUKI: 10,
  TANK: 30,
  TESLA: 24,
  TOYOTA: 16,
  UAZ: 9,
  VOLKSWAGEN: 16,
  VOYAH: 26,
  ZEEKR: 28,
  ГАЗ: 11,
};
